[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = ""
healthcheckTimeout = 0
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NIXPACKS_PKGS = "ffmpeg"
